development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: bubby_development
  pool: 10
  username: root
  password: ""
  host: localhost
  socket: /tmp/mysql.sock
#  socket: /var/lib/mysql/mysql.sock



 
production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: bubby_final
  pool: 10
  username: root
  password: ""
  host: localhost
  socket:  /opt/local/var/run/mysql5/mysqld.sock
